name: crystal_env
channels:
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - pip
  - python=3.11
  - setuptools
  - pip:
      - autogluon
      - beautifulsoup4
      - catboost
      - darts
      - datasets
      - decorator
      - entsoe-py
      - fastai
      - fastcore
      - gluonts
      - google-api-core
      - google-auth
      - gurobipy
      - holidays
      - huggingface-hub
      - hyperopt
      - ipython
      - jedi
      - jinja2
      - matplotlib
      - mlforecast
      - numba
      - numpy
      - nvidia-ml-py3
      - omegaconf
      - optuna
      - pyomo
      - pyyaml
      - ray
      - requests
      - rich
      - scikit-learn
      - scipy
      - sqlalchemy
      - statsforecast
      - statsmodels
      - tensorboard
      - tsfresh
      - xarray
      - xgboost
